package com.velp.infrastructure.parser;

import com.velp.domain.model.SubtitleLine;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class SubtitleFileParserTest {

    private final SubtitleFileParser parser = new SubtitleFileParser();

    @Test
    void parsesSrtCommaMilliseconds() {
        String content = """
                1
                00:00:01,250 --> 00:00:03,500
                Hello world.

                2
                00:00:04,000 --> 00:00:05,750
                Next line.
                """;

        List<SubtitleLine> lines = parser.parseContent(content, "srt", "en");

        assertThat(lines).hasSize(2);
        assertThat(lines.get(0).getStartTime()).isEqualTo(1.25);
        assertThat(lines.get(0).getEndTime()).isEqualTo(3.5);
        assertThat(lines.get(0).getEffectiveSourceText()).isEqualTo("Hello world.");
    }

    @Test
    void parsesVttCueSettingsAndCleansTags() {
        String content = """
                WEBVTT

                00:00:02.000 --> 00:00:04.000 align:start position:0%
                <v Speaker>Hello <b>there</b>&lrm;
                second row
                """;

        List<SubtitleLine> lines = parser.parseContent(content, "vtt", "en");

        assertThat(lines).hasSize(1);
        assertThat(lines.get(0).getStartTime()).isEqualTo(2.0);
        assertThat(lines.get(0).getEndTime()).isEqualTo(4.0);
        assertThat(lines.get(0).getEffectiveSourceText()).isEqualTo("Hello there second row");
    }

    @Test
    void skipsVttNoteStyleAndRegionBlocks() {
        String content = """
                WEBVTT

                NOTE generated by service
                should not become a cue

                STYLE
                ::cue { color: red; }

                REGION
                id:main

                00:00:06.000 --> 00:00:08.000
                Real subtitle.
                """;

        List<SubtitleLine> lines = parser.parseContent(content, "vtt", "en");

        assertThat(lines).hasSize(1);
        assertThat(lines.get(0).getEffectiveSourceText()).isEqualTo("Real subtitle.");
    }

    @Test
    void ignoresInvalidOrEmptyCues() {
        String content = """
                00:00:04.000 --> 00:00:04.000
                zero duration

                not timing
                text only
                """;

        assertThat(parser.parseContent(content, "vtt", "en")).isEmpty();
    }

    @Test
    void sortsCuesAndClampsOverlappingStartTimes() {
        String content = """
                00:00:05.000 --> 00:00:07.000
                later

                00:00:01.000 --> 00:00:03.000
                first

                00:00:02.500 --> 00:00:04.000
                overlap
                """;

        List<SubtitleLine> lines = parser.parseContent(content, "vtt", "en");

        assertThat(lines).hasSize(3);
        assertThat(lines.get(0).getEffectiveSourceText()).isEqualTo("first");
        assertThat(lines.get(1).getStartTime()).isEqualTo(3.0);
        assertThat(lines.get(1).getEndTime()).isEqualTo(4.0);
        assertThat(lines.get(2).getStartTime()).isEqualTo(5.0);
    }

    @Test
    void dropsDuplicateCuesWithSameTimingAndText() {
        String content = """
                00:00:01.000 --> 00:00:03.000
                repeated line

                00:00:01.000 --> 00:00:03.000
                repeated   line

                00:00:03.500 --> 00:00:04.000
                next
                """;

        List<SubtitleLine> lines = parser.parseContent(content, "vtt", "en");

        assertThat(lines).hasSize(2);
        assertThat(lines.get(0).getEffectiveSourceText()).isEqualTo("repeated line");
        assertThat(lines.get(1).getEffectiveSourceText()).isEqualTo("next");
    }
}
